import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mvpupdatedapp/generated30_trainerwidget/generated/GeneratedFrame650Widget7.dart';
import 'package:flutterapp/mvpupdatedapp/generated30_trainerwidget/generated/GeneratedComponent60Widget19.dart';
import 'package:flutterapp/mvpupdatedapp/generated30_trainerwidget/generated/GeneratedFrame640Widget4.dart';
import 'package:flutterapp/mvpupdatedapp/generated30_trainerwidget/generated/GeneratedTitleWidget32.dart';
import 'package:flutterapp/mvpupdatedapp/generated30_trainerwidget/generated/GeneratedComponent60Widget15.dart';
import 'package:flutterapp/mvpupdatedapp/generated30_trainerwidget/generated/GeneratedComponent60Widget17.dart';
import 'package:flutterapp/mvpupdatedapp/generated30_trainerwidget/generated/GeneratedEnterinformationofsportWidget.dart';
import 'package:flutterapp/mvpupdatedapp/generated30_trainerwidget/generated/GeneratedComponent63Widget1.dart';
import 'package:flutterapp/mvpupdatedapp/generated30_trainerwidget/generated/GeneratedComponent62Widget1.dart';
import 'package:flutterapp/mvpupdatedapp/generated30_trainerwidget/generated/GeneratedComponent60Widget18.dart';
import 'package:flutterapp/mvpupdatedapp/generated30_trainerwidget/generated/GeneratedAddphotoWidget.dart';
import 'package:flutterapp/mvpupdatedapp/generated30_trainerwidget/generated/GeneratedComponent60Widget16.dart';
import 'package:flutterapp/mvpupdatedapp/generated30_trainerwidget/generated/GeneratedNoteWidget.dart';
import 'package:flutterapp/mvpupdatedapp/generated30_trainerwidget/generated/GeneratedComponent61Widget3.dart';
import 'package:flutterapp/mvpupdatedapp/generated30_trainerwidget/generated/GeneratedInputtextWidget1.dart';

/* Frame 30_Trainer
    Autogenerated by FlutLab FTF Generator
  */
class Generated30_TrainerWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1506.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 390.0,
                      height: 1506.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 25.0,
                              top: 439.0,
                              right: 25.0,
                              bottom: null,
                              width: null,
                              height: 55.0,
                              child: GeneratedComponent60Widget15(),
                            ),
                            Positioned(
                              left: 25.0,
                              top: 533.0,
                              right: 25.0,
                              bottom: null,
                              width: null,
                              height: 54.0,
                              child: GeneratedComponent60Widget16(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 626.0,
                              right: 23.0,
                              bottom: null,
                              width: null,
                              height: 54.0,
                              child: GeneratedComponent61Widget3(),
                            ),
                            Positioned(
                              left: 28.0,
                              top: 719.0,
                              right: 22.0,
                              bottom: null,
                              width: null,
                              height: 54.0,
                              child: GeneratedComponent62Widget1(),
                            ),
                            Positioned(
                              left: 28.0,
                              top: 812.0,
                              right: 22.0,
                              bottom: null,
                              width: null,
                              height: 54.0,
                              child: GeneratedComponent63Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 104.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 24.0,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.7282051282051282;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.0641025641025641,
                                      y: 0,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        child:
                                            GeneratedEnterinformationofsportWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: null,
                              right: null,
                              bottom: 0.0,
                              width: 390.0,
                              height: 92.0,
                              child: GeneratedFrame640Widget4(),
                            ),
                            Positioned(
                              left: 25.0,
                              top: 346.0,
                              right: 39.0,
                              bottom: null,
                              width: null,
                              height: 54.0,
                              child: GeneratedComponent60Widget17(),
                            ),
                            Positioned(
                              left: 25.0,
                              top: 252.0,
                              right: 39.0,
                              bottom: null,
                              width: null,
                              height: 55.0,
                              child: GeneratedComponent60Widget18(),
                            ),
                            Positioned(
                              left: 25.0,
                              top: 159.0,
                              right: 25.0,
                              bottom: null,
                              width: null,
                              height: 54.0,
                              child: GeneratedComponent60Widget19(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 55.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 41.0,
                              child: GeneratedTitleWidget32(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 886.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 28.0,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.46923076923076923;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.07692307692307693,
                                      y: 0,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        child: GeneratedNoteWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 25.0,
                              top: 948.0,
                              right: 25.0,
                              bottom: null,
                              width: null,
                              height: 201.0,
                              child: GeneratedInputtextWidget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1188.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 25.0,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.26153846153846155;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.07948717948717948,
                                      y: 0,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        child: GeneratedAddphotoWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 119.0,
                              top: 1250.0,
                              right: null,
                              bottom: null,
                              width: 112.0,
                              height: 104.0,
                              child: GeneratedFrame650Widget7(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
