import 'package:flutter/material.dart';
import 'package:flutterapp/mvpupdatedapp/generated20_findsportswidget/generated/GeneratedComponent63Widget.dart';
import 'package:flutterapp/mvpupdatedapp/generated20_findsportswidget/generated/GeneratedComponent60Widget7.dart';
import 'package:flutterapp/mvpupdatedapp/generated20_findsportswidget/generated/GeneratedComponent62Widget.dart';
import 'package:flutterapp/mvpupdatedapp/generated20_findsportswidget/generated/GeneratedFrame640Widget.dart';
import 'package:flutterapp/mvpupdatedapp/generated20_findsportswidget/generated/GeneratedTitleWidget14.dart';
import 'package:flutterapp/mvpupdatedapp/generated20_findsportswidget/generated/GeneratedFrame642Widget1.dart';
import 'package:flutterapp/mvpupdatedapp/generated20_findsportswidget/generated/GeneratedComponent64Widget.dart';
import 'package:flutterapp/mvpupdatedapp/generated20_findsportswidget/generated/GeneratedComponent65Widget.dart';
import 'package:flutterapp/mvpupdatedapp/generated20_findsportswidget/generated/GeneratedComponent6Widget5.dart';
import 'package:flutterapp/mvpupdatedapp/generated20_findsportswidget/generated/GeneratedComponent61Widget1.dart';

/* Frame 20_find sports
    Autogenerated by FlutLab FTF Generator
  */
class Generated20_findsportsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          clipBehavior: Clip.none,
          fit: StackFit.expand,
          alignment: Alignment.center,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 887.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 375.0,
                            height: 887.0,
                            child: Stack(
                                clipBehavior: Clip.none,
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 248, 251, 250),
                                    ),
                                  ),
                                  Positioned(
                                    left: 20.0,
                                    top: 175.0,
                                    right: 13.0,
                                    bottom: null,
                                    width: null,
                                    height: 56.0,
                                    child: GeneratedComponent60Widget7(),
                                  ),
                                  Positioned(
                                    left: 20.0,
                                    top: 263.0,
                                    right: 13.0,
                                    bottom: null,
                                    width: null,
                                    height: 56.0,
                                    child: GeneratedComponent64Widget(),
                                  ),
                                  Positioned(
                                    left: 20.0,
                                    top: 351.0,
                                    right: 13.0,
                                    bottom: null,
                                    width: null,
                                    height: 56.0,
                                    child: GeneratedComponent61Widget1(),
                                  ),
                                  Positioned(
                                    left: 20.0,
                                    top: 535.0,
                                    right: 13.0,
                                    bottom: null,
                                    width: null,
                                    height: 56.0,
                                    child: GeneratedComponent62Widget(),
                                  ),
                                  Positioned(
                                    left: 20.0,
                                    top: 627.0,
                                    right: 13.0,
                                    bottom: null,
                                    width: null,
                                    height: 70.0,
                                    child: GeneratedComponent65Widget(),
                                  ),
                                  Positioned(
                                    left: 20.0,
                                    top: 439.0,
                                    right: 13.0,
                                    bottom: null,
                                    width: null,
                                    height: 56.0,
                                    child: GeneratedComponent63Widget(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: null,
              right: null,
              bottom: 0.0,
              width: 375.0,
              height: 70.0,
              child: GeneratedComponent6Widget5(),
            ),
            Positioned(
              left: 0.0,
              top: null,
              right: null,
              bottom: 70.0,
              width: 375.0,
              height: 94.0,
              child: GeneratedFrame640Widget(),
            ),
            Positioned(
              left: 24.0,
              top: 96.0,
              right: null,
              bottom: null,
              width: 327.0,
              height: 39.0,
              child: GeneratedFrame642Widget1(),
            ),
            Positioned(
              left: 0.0,
              top: 44.0,
              right: 0.0,
              bottom: null,
              width: null,
              height: 42.0,
              child: GeneratedTitleWidget14(),
            )
          ]),
    ));
  }
}
