import 'package:flutter/material.dart';
import 'package:flutterapp/mvpupdatedapp/generated21_findsportswidget/generated/GeneratedComponent50Widget.dart';
import 'package:flutterapp/mvpupdatedapp/generated21_findsportswidget/generated/GeneratedComponent51Widget.dart';
import 'package:flutterapp/mvpupdatedapp/generated21_findsportswidget/generated/GeneratedComponent2Widget13.dart';
import 'package:flutterapp/mvpupdatedapp/generated21_findsportswidget/generated/GeneratedComponent52Widget.dart';
import 'package:flutterapp/mvpupdatedapp/generated21_findsportswidget/generated/GeneratedFrame49Widget1.dart';
import 'package:flutterapp/mvpupdatedapp/generated21_findsportswidget/generated/GeneratedFrame634Widget1.dart';
import 'package:flutterapp/mvpupdatedapp/generated21_findsportswidget/generated/GeneratedComponent48Widget.dart';
import 'package:flutterapp/mvpupdatedapp/generated21_findsportswidget/generated/GeneratedComponent53Widget.dart';
import 'package:flutterapp/mvpupdatedapp/generated21_findsportswidget/generated/GeneratedComponent49Widget.dart';
import 'package:flutterapp/mvpupdatedapp/generated21_findsportswidget/generated/GeneratedSelectsportthatyourtrainWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mvpupdatedapp/generated21_findsportswidget/generated/GeneratedComponent54Widget.dart';
import 'package:flutterapp/mvpupdatedapp/generated21_findsportswidget/generated/GeneratedComponent55Widget.dart';

/* Frame 21_find sports
    Autogenerated by FlutLab FTF Generator
  */
class Generated21_findsportsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          clipBehavior: Clip.none,
          fit: StackFit.expand,
          alignment: Alignment.center,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 812.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 375.0,
                            height: 812.0,
                            child: Stack(
                                clipBehavior: Clip.none,
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 248, 251, 250),
                                    ),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 128.0,
                                    child: GeneratedFrame49Widget1(),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: 146.0,
                                    right: null,
                                    bottom: null,
                                    width: 249.0,
                                    height: 25.0,
                                    child: TransformHelper.translate(
                                        x: -39.00,
                                        y: 0.00,
                                        z: 0,
                                        child:
                                            GeneratedSelectsportthatyourtrainWidget()),
                                  ),
                                  Positioned(
                                    left: 24.0,
                                    top: 718.0,
                                    right: null,
                                    bottom: null,
                                    width: 327.0,
                                    height: 54.0,
                                    child: GeneratedComponent2Widget13(),
                                  ),
                                  Positioned(
                                    left: 24.0,
                                    top: 243.0,
                                    right: null,
                                    bottom: null,
                                    width: 327.0,
                                    height: 55.0,
                                    child: GeneratedComponent48Widget(),
                                  ),
                                  Positioned(
                                    left: 24.0,
                                    top: 298.0,
                                    right: null,
                                    bottom: null,
                                    width: 327.0,
                                    height: 55.0,
                                    child: GeneratedComponent49Widget(),
                                  ),
                                  Positioned(
                                    left: 24.0,
                                    top: 353.0,
                                    right: null,
                                    bottom: null,
                                    width: 327.0,
                                    height: 55.0,
                                    child: GeneratedComponent50Widget(),
                                  ),
                                  Positioned(
                                    left: 24.0,
                                    top: 408.0,
                                    right: null,
                                    bottom: null,
                                    width: 327.0,
                                    height: 55.0,
                                    child: GeneratedComponent51Widget(),
                                  ),
                                  Positioned(
                                    left: 24.0,
                                    top: 463.0,
                                    right: null,
                                    bottom: null,
                                    width: 327.0,
                                    height: 55.0,
                                    child: GeneratedComponent52Widget(),
                                  ),
                                  Positioned(
                                    left: 24.0,
                                    top: 518.0,
                                    right: null,
                                    bottom: null,
                                    width: 327.0,
                                    height: 55.0,
                                    child: GeneratedComponent53Widget(),
                                  ),
                                  Positioned(
                                    left: 24.0,
                                    top: 573.0,
                                    right: null,
                                    bottom: null,
                                    width: 327.0,
                                    height: 55.0,
                                    child: GeneratedComponent54Widget(),
                                  ),
                                  Positioned(
                                    left: 24.0,
                                    top: 628.0,
                                    right: null,
                                    bottom: null,
                                    width: 327.0,
                                    height: 55.0,
                                    child: GeneratedComponent55Widget(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: 177.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 67.0,
              child: GeneratedFrame634Widget1(),
            )
          ]),
    ));
  }
}
