import 'package:flutter/material.dart';
import 'package:flutterapp/mvpupdatedapp/generated24_findsportswidget/generated/GeneratedComponent4Widget46.dart';
import 'package:flutterapp/mvpupdatedapp/generated24_findsportswidget/generated/GeneratedFrame694Widget.dart';
import 'package:flutterapp/mvpupdatedapp/generated24_findsportswidget/generated/GeneratedFrame696Widget.dart';
import 'package:flutterapp/mvpupdatedapp/generated24_findsportswidget/generated/GeneratedFrame693Widget.dart';
import 'package:flutterapp/mvpupdatedapp/generated24_findsportswidget/generated/GeneratedFrame49Widget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mvpupdatedapp/generated24_findsportswidget/generated/GeneratedFrame695Widget.dart';

/* Frame 24_find sports
    Autogenerated by FlutLab FTF Generator
  */
class Generated24_findsportsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          clipBehavior: Clip.none,
          fit: StackFit.expand,
          alignment: Alignment.center,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1861.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 375.0,
                            height: 1861.0,
                            child: Stack(
                                clipBehavior: Clip.none,
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 248, 251, 250),
                                    ),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: null,
                                    right: 61.0,
                                    bottom: null,
                                    width: 24.0,
                                    height: 24.0,
                                    child: TransformHelper.translate(
                                        x: 0.00,
                                        y: -883.50,
                                        z: 0,
                                        child: GeneratedComponent4Widget46()),
                                  ),
                                  Positioned(
                                    left: 24.0,
                                    top: 128.0,
                                    right: null,
                                    bottom: null,
                                    width: 327.00006103515625,
                                    height: 411.0,
                                    child: GeneratedFrame693Widget(),
                                  ),
                                  Positioned(
                                    left: 24.0,
                                    top: 559.0,
                                    right: null,
                                    bottom: null,
                                    width: 327.00006103515625,
                                    height: 411.0,
                                    child: GeneratedFrame694Widget(),
                                  ),
                                  Positioned(
                                    left: 24.0,
                                    top: 990.0,
                                    right: null,
                                    bottom: null,
                                    width: 327.00006103515625,
                                    height: 411.0,
                                    child: GeneratedFrame695Widget(),
                                  ),
                                  Positioned(
                                    left: 24.0,
                                    top: 1421.0,
                                    right: null,
                                    bottom: null,
                                    width: 327.00006103515625,
                                    height: 411.0,
                                    child: GeneratedFrame696Widget(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 128.0,
              child: GeneratedFrame49Widget2(),
            )
          ]),
    ));
  }
}
