import 'package:flutter/material.dart';
import 'package:flutterapp/mvpupdatedapp/generated35_requestswidget/generated/GeneratedFrame49Widget5.dart';
import 'package:flutterapp/mvpupdatedapp/generated35_requestswidget/generated/GeneratedFrame614Widget9.dart';
import 'package:flutterapp/mvpupdatedapp/generated35_requestswidget/generated/GeneratedRequestslistWidget.dart';
import 'package:flutterapp/mvpupdatedapp/generated35_requestswidget/generated/GeneratedRequestsWidget1.dart';
import 'package:flutterapp/mvpupdatedapp/generated35_requestswidget/generated/GeneratedTitleWidget39.dart';
import 'package:flutterapp/mvpupdatedapp/generated35_requestswidget/generated/GeneratedFrame613Widget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame 35_REQUESTS
    Autogenerated by FlutLab FTF Generator
  */
class Generated35_REQUESTSWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1098.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 390.0,
                      height: 1098.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 208.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 221.0,
                              child: GeneratedFrame613Widget2(),
                            ),
                            Positioned(
                              left: 25.0,
                              top: 465.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 221.0,
                              child: GeneratedFrame614Widget9(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 128.0,
                              child: GeneratedFrame49Widget5(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 66.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 42.0,
                              child: GeneratedTitleWidget39(),
                            ),
                            Positioned(
                              left: null,
                              top: 136.0,
                              right: null,
                              bottom: null,
                              width: 334.0,
                              height: 59.0,
                              child: TransformHelper.translate(
                                  x: 3.00,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedRequestslistWidget()),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 1007.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 54.0,
                              child: GeneratedRequestsWidget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
