import 'package:flutter/material.dart';
import 'package:flutterapp/mvpupdatedapp/generated22_findsportswidget/generated/GeneratedFrame642Widget2.dart';
import 'package:flutterapp/mvpupdatedapp/generated22_findsportswidget/generated/GeneratedTitleWidget18.dart';
import 'package:flutterapp/mvpupdatedapp/generated22_findsportswidget/generated/GeneratedComponent60Widget8.dart';
import 'package:flutterapp/mvpupdatedapp/generated22_findsportswidget/generated/GeneratedComponent61Widget2.dart';
import 'package:flutterapp/mvpupdatedapp/generated22_findsportswidget/generated/GeneratedComponent6Widget6.dart';

/* Frame 22_find sports
    Autogenerated by FlutLab FTF Generator
  */
class Generated22_findsportsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1292.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1292.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 248, 251, 250),
                              ),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 696.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 482.0,
                              child: GeneratedComponent61Widget2(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 181.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 482.0,
                              child: GeneratedComponent60Widget8(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 96.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 39.0,
                              child: GeneratedFrame642Widget2(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: null,
                              right: null,
                              bottom: 0.0,
                              width: 375.0,
                              height: 65.0,
                              child: GeneratedComponent6Widget6(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 44.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 42.0,
                              child: GeneratedTitleWidget18(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
