description: "A new Flutter application."
name: "flutterapp"

publish_to: "none"

version: "1.0.0+1"

dependencies:
  cloud_firestore: ^4.0.5
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.1.2
  firebase_core: ^2.2.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.1.1
  path_drawing: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: "flutter"

environment:
  sdk: ">=2.12.0 <3.0.0"
flutter:
  assets:
    - "assets/images/"
  fonts:
    - family: "Inter"
      fonts:
        - asset: "fonts/Inter-500.ttf"
          style: "normal"
          weight: 500
        - asset: "fonts/Inter-regular.ttf"
          style: "normal"
          weight: 400
        - asset: "fonts/Inter-700.ttf"
          style: "normal"
          weight: 700
    - family: "Actor"
      fonts:
        - asset: "fonts/Actor-regular.ttf"
          style: "normal"
          weight: 400
  uses-material-design: true
