import 'package:flutter/material.dart';
import 'package:flutterapp/mvpupdatedapp/generated23_findsportswidget/generated/GeneratedFrame644Widget.dart';
import 'package:flutterapp/mvpupdatedapp/generated23_findsportswidget/generated/GeneratedRectangle853Widget43.dart';
import 'package:flutterapp/mvpupdatedapp/generated23_findsportswidget/generated/GeneratedRectangle854Widget13.dart';
import 'package:flutterapp/mvpupdatedapp/generated23_findsportswidget/generated/GeneratedComponent6Widget7.dart';
import 'package:flutterapp/mvpupdatedapp/generated23_findsportswidget/generated/GeneratedHapoelHolonRowingWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mvpupdatedapp/generated23_findsportswidget/generated/GeneratedComponent22Widget3.dart';
import 'package:flutterapp/mvpupdatedapp/generated23_findsportswidget/generated/GeneratedIcWidget8.dart';
import 'package:flutterapp/mvpupdatedapp/generated23_findsportswidget/generated/GeneratedTitleWidget20.dart';
import 'package:flutterapp/mvpupdatedapp/generated23_findsportswidget/generated/GeneratedForgotpasswordWidget3.dart';
import 'package:flutterapp/mvpupdatedapp/generated23_findsportswidget/generated/GeneratedFrame650Widget6.dart';

/* Frame 23_find sports
    Autogenerated by FlutLab FTF Generator
  */
class Generated23_findsportsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          clipBehavior: Clip.none,
          fit: StackFit.expand,
          alignment: Alignment.center,
          children: [
            Container(
              width: 375.0,
              height: 1642.0,
              child: Stack(
                  clipBehavior: Clip.none,
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 248, 251, 250),
                      ),
                    ),
                    Positioned(
                      left: 351.00006103515625,
                      top: 1142.0,
                      right: null,
                      bottom: null,
                      width: 327.00006103515625,
                      height: 835.9999389648438,
                      child: GeneratedRectangle854Widget13(),
                    ),
                    Positioned(
                      left: 235.00006103515625,
                      top: 440.0,
                      right: null,
                      bottom: null,
                      width: 104.0,
                      height: 16.0,
                      child: GeneratedForgotpasswordWidget3(),
                    ),
                    Positioned(
                      left: 40.00006103515625,
                      top: 478.0,
                      right: null,
                      bottom: null,
                      width: 299.0,
                      height: 625.0,
                      child: GeneratedFrame650Widget6(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: null,
                      bottom: null,
                      width: 375.0,
                      height: 265.0,
                      child: GeneratedRectangle853Widget43(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 324.0,
                      right: 0.0,
                      bottom: null,
                      width: null,
                      height: 54.0,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width = constraints.maxWidth * 0.808;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.09600016276041666,
                              y: 0,
                              z: 0,
                              child: Container(
                                width: width,
                                child: GeneratedComponent22Widget3(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 34.0,
                      right: 0.0,
                      bottom: null,
                      width: null,
                      height: 231.0,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.8453333333333334;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.07466666666666667,
                              y: 0,
                              z: 0,
                              child: Container(
                                width: width,
                                child: GeneratedIcWidget8(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 1206.0,
                      right: null,
                      bottom: null,
                      width: 375.0,
                      height: 327.0,
                      child: GeneratedFrame644Widget(),
                    ),
                    Positioned(
                      left: 52.0,
                      top: 154.0,
                      right: null,
                      bottom: null,
                      width: 262.0,
                      height: 52.0,
                      child: GeneratedHapoelHolonRowingWidget2(),
                    ),
                    Positioned(
                      left: 1.0,
                      top: null,
                      right: null,
                      bottom: 0.0,
                      width: 375.0,
                      height: 64.0,
                      child: GeneratedComponent6Widget7(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 44.0,
              right: 0.0,
              bottom: null,
              width: null,
              height: 42.0,
              child: GeneratedTitleWidget20(),
            )
          ]),
    ));
  }
}
