import 'package:flutter/material.dart';
import 'package:flutterapp/mvpupdatedapp/generated17_childprofilewidget/generated/GeneratedNowisthetimetochooseasportclubWidget.dart';
import 'package:flutterapp/mvpupdatedapp/generated17_childprofilewidget/generated/GeneratedFrame650Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mvpupdatedapp/generated17_childprofilewidget/generated/GeneratedComponent4Widget38.dart';
import 'package:flutterapp/mvpupdatedapp/generated17_childprofilewidget/generated/GeneratedFrame653Widget.dart';
import 'package:flutterapp/mvpupdatedapp/generated17_childprofilewidget/generated/GeneratedJeremiahsprofilesuccessfullyaddedWidget.dart';
import 'package:flutterapp/mvpupdatedapp/generated17_childprofilewidget/generated/GeneratedComponent2Widget12.dart';

/* Frame 17_child profile
    Autogenerated by FlutLab FTF Generator
  */
class Generated17_childprofileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child: Stack(
            clipBehavior: Clip.none,
            fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 83, 219, 146),
                ),
              ),
              Positioned(
                left: 8.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 464.0,
                child: GeneratedFrame653Widget(),
              ),
              Positioned(
                left: 54.0,
                top: 508.0,
                right: null,
                bottom: null,
                width: 288.0,
                height: 48.0,
                child: GeneratedNowisthetimetochooseasportclubWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.6897435897435897;

                  final double height =
                      constraints.maxHeight * 0.06753554502369669;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.16153846153846155,
                        y: constraints.maxHeight * 0.5248815165876777,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child:
                              GeneratedJeremiahsprofilesuccessfullyaddedWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 33.0,
                top: 611.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 54.0,
                child: GeneratedComponent2Widget12(),
              ),
              Positioned(
                left: 31.0,
                top: 722.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 54.0,
                child: GeneratedComponent4Widget38(),
              ),
              Positioned(
                left: 153.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 102.0,
                height: 102.0,
                child: GeneratedFrame650Widget(),
              )
            ]),
      ),
    ));
  }
}
