import 'package:flutter/material.dart';
import 'package:flutterapp/mvpupdatedapp/generated19_findsportswidget/generated/GeneratedComponent6Widget4.dart';
import 'package:flutterapp/mvpupdatedapp/generated19_findsportswidget/generated/GeneratedTitleWidget12.dart';
import 'package:flutterapp/mvpupdatedapp/generated19_findsportswidget/generated/GeneratedInfoblockWidget2.dart';
import 'package:flutterapp/mvpupdatedapp/generated19_findsportswidget/generated/GeneratedFrame642Widget.dart';
import 'package:flutterapp/mvpupdatedapp/generated19_findsportswidget/generated/GeneratedFrame639Widget.dart';

/* Frame 19_find sports
    Autogenerated by FlutLab FTF Generator
  */
class Generated19_findsportsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          clipBehavior: Clip.none,
          fit: StackFit.expand,
          alignment: Alignment.center,
          children: [
            Container(
              width: 390.0,
              height: 1022.0,
              child: Stack(
                  clipBehavior: Clip.none,
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 248, 251, 250),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: null,
                      right: null,
                      bottom: 0.0,
                      width: 390.0,
                      height: 67.0,
                      child: GeneratedComponent6Widget4(),
                    ),
                    Positioned(
                      left: 26.0,
                      top: 135.0,
                      right: null,
                      bottom: null,
                      width: 327.0,
                      height: 199.0,
                      child: GeneratedInfoblockWidget2(),
                    ),
                    Positioned(
                      left: 24.0,
                      top: 378.0,
                      right: null,
                      bottom: null,
                      width: 327.0,
                      height: 39.0,
                      child: GeneratedFrame642Widget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 437.0,
                      right: null,
                      bottom: null,
                      width: 375.0,
                      height: 479.0,
                      child: GeneratedFrame639Widget(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 61.0,
              right: 0.0,
              bottom: null,
              width: null,
              height: 42.0,
              child: GeneratedTitleWidget12(),
            )
          ]),
    ));
  }
}
