import 'package:flutter/material.dart';
import 'package:flutterapp/mvpupdatedapp/generated31_trainerwidget/generated/GeneratedComponent54Widget1.dart';
import 'package:flutterapp/mvpupdatedapp/generated31_trainerwidget/generated/GeneratedComponent51Widget1.dart';
import 'package:flutterapp/mvpupdatedapp/generated31_trainerwidget/generated/GeneratedTitleWidget34.dart';
import 'package:flutterapp/mvpupdatedapp/generated31_trainerwidget/generated/GeneratedComponent50Widget1.dart';
import 'package:flutterapp/mvpupdatedapp/generated31_trainerwidget/generated/GeneratedComponent49Widget1.dart';
import 'package:flutterapp/mvpupdatedapp/generated31_trainerwidget/generated/GeneratedSelectsportthatyourtrainWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mvpupdatedapp/generated31_trainerwidget/generated/GeneratedFrame634Widget3.dart';
import 'package:flutterapp/mvpupdatedapp/generated31_trainerwidget/generated/GeneratedComponent55Widget1.dart';
import 'package:flutterapp/mvpupdatedapp/generated31_trainerwidget/generated/GeneratedComponent52Widget1.dart';
import 'package:flutterapp/mvpupdatedapp/generated31_trainerwidget/generated/GeneratedComponent53Widget1.dart';
import 'package:flutterapp/mvpupdatedapp/generated31_trainerwidget/generated/GeneratedComponent2Widget17.dart';
import 'package:flutterapp/mvpupdatedapp/generated31_trainerwidget/generated/GeneratedComponent48Widget1.dart';

/* Frame 31_Trainer
    Autogenerated by FlutLab FTF Generator
  */
class Generated31_TrainerWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 844.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 390.0,
                      height: 844.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 64.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 42.0,
                              child: GeneratedTitleWidget34(),
                            ),
                            Positioned(
                              left: null,
                              top: 144.0,
                              right: null,
                              bottom: null,
                              width: 249.0,
                              height: 25.0,
                              child: TransformHelper.translate(
                                  x: -39.50,
                                  y: 0.00,
                                  z: 0,
                                  child:
                                      GeneratedSelectsportthatyourtrainWidget1()),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 716.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 54.0,
                              child: GeneratedComponent2Widget17(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 241.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 55.0,
                              child: GeneratedComponent48Widget1(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 296.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 55.0,
                              child: GeneratedComponent49Widget1(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 351.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 55.0,
                              child: GeneratedComponent50Widget1(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 406.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 55.0,
                              child: GeneratedComponent51Widget1(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 461.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 55.0,
                              child: GeneratedComponent52Widget1(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 516.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 55.0,
                              child: GeneratedComponent53Widget1(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 571.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 55.0,
                              child: GeneratedComponent54Widget1(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 626.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 55.0,
                              child: GeneratedComponent55Widget1(),
                            ),
                            Positioned(
                              left: 7.0,
                              top: 175.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 67.0,
                              child: GeneratedFrame634Widget3(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
