import 'package:flutter/material.dart';
import 'package:flutterapp/mvpupdatedapp/generated34_trainerwidget/generated/GeneratedAddsportWidget1.dart';
import 'package:flutterapp/mvpupdatedapp/generated34_trainerwidget/generated/GeneratedRequestsWidget.dart';
import 'package:flutterapp/mvpupdatedapp/generated34_trainerwidget/generated/GeneratedSport1Widget.dart';
import 'package:flutterapp/mvpupdatedapp/generated34_trainerwidget/generated/GeneratedAddsportWidget.dart';
import 'package:flutterapp/mvpupdatedapp/generated34_trainerwidget/generated/GeneratedNameWidget.dart';
import 'package:flutterapp/mvpupdatedapp/generated34_trainerwidget/generated/GeneratedToolbarWidget.dart';

/* Frame 34_Trainer
    Autogenerated by FlutLab FTF Generator
  */
class Generated34_TrainerWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 933.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 390.0,
                      height: 933.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 766.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 54.0,
                              child: GeneratedAddsportWidget(),
                            ),
                            Positioned(
                              left: 22.0,
                              top: 841.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 54.0,
                              child: GeneratedAddsportWidget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 691.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 54.0,
                              child: GeneratedRequestsWidget(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 172.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 485.0,
                              child: GeneratedSport1Widget(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 100.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 39.0,
                              child: GeneratedNameWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 38.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 42.0,
                              child: GeneratedToolbarWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
