import 'package:flutter/material.dart';
import 'package:flutterapp/mvpupdatedapp/generated40_trainermenuwidget/generated/GeneratedAddsportWidget.dart';
import 'package:flutterapp/mvpupdatedapp/generated40_trainermenuwidget/generated/GeneratedHUGINWidget.dart';
import 'package:flutterapp/mvpupdatedapp/generated40_trainermenuwidget/generated/GeneratedNameWidget.dart';
import 'package:flutterapp/mvpupdatedapp/generated40_trainermenuwidget/generated/GeneratedRequestsWidget.dart';

/* Frame 40_trainer menu
    Autogenerated by FlutLab FTF Generator
  */
class Generated40_trainermenuWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 933.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 390.0,
                      height: 933.0,
                      child: Stack(clipBehavior: Clip.none, fit: StackFit.expand, alignment: Alignment.center, children: [
                        ClipRRect(
                          borderRadius: BorderRadius.zero,
                          child: Container(
                            color: Color.fromARGB(255, 255, 255, 255),
                          ),
                        ),
                        Positioned(
                          left: 28.0,
                          top: 368.0,
                          right: null,
                          bottom: null,
                          width: 327.0,
                          height: 54.0,
                          child: GeneratedAddsportWidget(),
                        ),
                        Positioned(
                          left: 28.0,
                          top: 293.0,
                          right: null,
                          bottom: null,
                          width: 327.0,
                          height: 54.0,
                          child: GeneratedRequestsWidget(),
                        ),
                        Positioned(
                          left: 86.0,
                          top: 187.0,
                          right: null,
                          bottom: null,
                          width: 218.0,
                          height: 39.0,
                          child: GeneratedNameWidget(),
                        ),
                        Positioned(
                          left: 112.0,
                          top: 98.0,
                          right: null,
                          bottom: null,
                          width: 159.0,
                          height: 36.0,
                          child: GeneratedHUGINWidget(),
                        )
                      ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
