import 'package:flutter/material.dart';
import 'package:flutterapp/mvpupdatedapp/generated7_successwindowpasswordwidget/generated/GeneratedAccountsuccessfullyregisteredWidget.dart';
import 'package:flutterapp/mvpupdatedapp/generated7_successwindowpasswordwidget/generated/GeneratedComponent2Widget5.dart';
import 'package:flutterapp/mvpupdatedapp/generated7_successwindowpasswordwidget/generated/GeneratedPasswordsuccessfullyrecoveredWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame 7_success window password
    Autogenerated by FlutLab FTF Generator
  */
class Generated7_successwindowpasswordWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child: Stack(
            clipBehavior: Clip.none,
            fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 83, 219, 146),
                ),
              ),
              Positioned(
                left: 8.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 464.0,
                child: GeneratedAccountsuccessfullyregisteredWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.6897435897435897;

                  final double height =
                      constraints.maxHeight * 0.06753554502369669;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.13076923076923078,
                        y: constraints.maxHeight * 0.5699052132701422,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedPasswordsuccessfullyrecoveredWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4846153846153846;

                  final double height =
                      constraints.maxHeight * 0.06398104265402843;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.258974358974359,
                        y: constraints.maxHeight * 0.7488151658767772,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedComponent2Widget5(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
