import 'package:flutter/material.dart';
import 'package:flutterapp/mvpupdatedapp/generated32_trainerwidget/generated/GeneratedCheckwhattheuserwillseeinyourschoolcardandifthatscorrec.dart';
import 'package:flutterapp/mvpupdatedapp/generated32_trainerwidget/generated/GeneratedComponent57Widget.dart';
import 'package:flutterapp/mvpupdatedapp/generated32_trainerwidget/generated/GeneratedTitleWidget36.dart';
import 'package:flutterapp/mvpupdatedapp/generated32_trainerwidget/generated/GeneratedComponent2Widget18.dart';

/* Frame 32_Trainer
    Autogenerated by FlutLab FTF Generator
  */
class Generated32_TrainerWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 844.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 390.0,
                      height: 844.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 83, 219, 146),
                              ),
                            ),
                            Positioned(
                              left: 45.0,
                              top: 600.0,
                              right: null,
                              bottom: null,
                              width: 288.0,
                              height: 71.0,
                              child:
                                  GeneratedCheckwhattheuserwillseeinyourschoolcardandifthatscorrec(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 698.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 54.0,
                              child: GeneratedComponent2Widget18(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 99.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 479.0,
                              child: GeneratedComponent57Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 42.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 42.0,
                              child: GeneratedTitleWidget36(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
