import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mvpupdatedapp/generated10_createaccountwidget/generated/GeneratedInfoblockWidget1.dart';
import 'package:flutterapp/mvpupdatedapp/generated10_createaccountwidget/generated/GeneratedBackWidget11.dart';
import 'package:flutterapp/mvpupdatedapp/generated10_createaccountwidget/generated/GeneratedComponent2Widget8.dart';
import 'package:flutterapp/mvpupdatedapp/generated10_createaccountwidget/generated/GeneratedEnteryourphoneWidget.dart';
import 'package:flutterapp/mvpupdatedapp/generated10_createaccountwidget/generated/GeneratedEnterphonenumWidget1.dart';

/* Frame 10_create account
    Autogenerated by FlutLab FTF Generator
  */
class Generated10_createaccountWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child: Stack(
            clipBehavior: Clip.none,
            fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 3.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 33.0,
                child: GeneratedBackWidget11(),
              ),
              Positioned(
                left: 29.0,
                top: 430.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 54.0,
                child: GeneratedComponent2Widget8(),
              ),
              Positioned(
                left: null,
                top: 113.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 43.0,
                child: TransformHelper.translate(
                    x: 1.00,
                    y: 0.00,
                    z: 0,
                    child: GeneratedEnteryourphoneWidget()),
              ),
              Positioned(
                left: 29.0,
                top: 274.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 99.0,
                child: GeneratedInfoblockWidget1(),
              ),
              Positioned(
                left: 29.0,
                top: 186.0,
                right: 34.0,
                bottom: null,
                width: null,
                height: 56.0,
                child: GeneratedEnterphonenumWidget1(),
              )
            ]),
      ),
    ));
  }
}
