import 'package:flutter/material.dart';
import 'package:flutterapp/mvpupdatedapp/generated18_findsportswidget/generated/GeneratedTitleWidget10.dart';
import 'package:flutterapp/mvpupdatedapp/generated18_findsportswidget/generated/GeneratedFrame614Widget5.dart';
import 'package:flutterapp/mvpupdatedapp/generated18_findsportswidget/generated/GeneratedFrame49Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mvpupdatedapp/generated18_findsportswidget/generated/GeneratedComponent4Widget39.dart';
import 'package:flutterapp/mvpupdatedapp/generated18_findsportswidget/generated/GeneratedFrame615Widget7.dart';
import 'package:flutterapp/mvpupdatedapp/generated18_findsportswidget/generated/GeneratedSelectaprofileforwhichtofindactivityWidget.dart';
import 'package:flutterapp/mvpupdatedapp/generated18_findsportswidget/generated/GeneratedFrame613Widget1.dart';

/* Frame 18_find sports
    Autogenerated by FlutLab FTF Generator
  */
class Generated18_findsportsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 844.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 390.0,
                      height: 844.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 248, 251, 250),
                              ),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 208.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 140.0,
                              child: GeneratedFrame613Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 364.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 140.0,
                              child: GeneratedFrame614Widget5(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 520.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 140.0,
                              child: GeneratedFrame615Widget7(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 128.0,
                              child: GeneratedFrame49Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 66.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 42.0,
                              child: GeneratedTitleWidget10(),
                            ),
                            Positioned(
                              left: null,
                              top: 136.0,
                              right: null,
                              bottom: null,
                              width: 334.0,
                              height: 59.0,
                              child: TransformHelper.translate(
                                  x: 3.00,
                                  y: 0.00,
                                  z: 0,
                                  child:
                                      GeneratedSelectaprofileforwhichtofindactivityWidget()),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 722.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 54.0,
                              child: GeneratedComponent4Widget39(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
