import 'package:flutter/material.dart';
import 'package:flutterapp/mvpupdatedapp/generated5_forgotpasswordwidget/generated/GeneratedBackWidget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mvpupdatedapp/generated5_forgotpasswordwidget/generated/GeneratedComponent2Widget3.dart';
import 'package:flutterapp/mvpupdatedapp/generated5_forgotpasswordwidget/generated/GeneratedEnteracodeWidget.dart';
import 'package:flutterapp/mvpupdatedapp/generated5_forgotpasswordwidget/generated/GeneratedComponent7Widget.dart';
import 'package:flutterapp/mvpupdatedapp/generated5_forgotpasswordwidget/generated/GeneratedSystemFeedbackblockWidget.dart';

/* Frame 5_forgot password
    Autogenerated by FlutLab FTF Generator
  */
class Generated5_forgotpasswordWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child: Stack(
            clipBehavior: Clip.none,
            fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 33.0,
                child: GeneratedBackWidget4(),
              ),
              Positioned(
                left: null,
                top: 115.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 43.0,
                child: TransformHelper.translate(
                    x: 1.00, y: 0.00, z: 0, child: GeneratedEnteracodeWidget()),
              ),
              Positioned(
                left: 29.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 78.0,
                child: GeneratedSystemFeedbackblockWidget(),
              ),
              Positioned(
                left: 29.0,
                top: 196.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 56.0,
                child: GeneratedComponent7Widget(),
              ),
              Positioned(
                left: 31.0,
                top: 428.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 54.0,
                child: GeneratedComponent2Widget3(),
              )
            ]),
      ),
    ));
  }
}
