import 'package:flutter/material.dart';
import 'package:flutterapp/mvpupdatedapp/generated15_childprofilewidget/generated/GeneratedSearchFieldWidget1.dart';
import 'package:flutterapp/mvpupdatedapp/generated15_childprofilewidget/generated/GeneratedFrame616Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mvpupdatedapp/generated15_childprofilewidget/generated/GeneratedSelectyourcityWidget1.dart';
import 'package:flutterapp/mvpupdatedapp/generated15_childprofilewidget/generated/GeneratedComponent2Widget10.dart';
import 'package:flutterapp/mvpupdatedapp/generated15_childprofilewidget/generated/GeneratedBackWidget16.dart';

/* Frame 15_child profile
    Autogenerated by FlutLab FTF Generator
  */
class Generated15_childprofileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 844.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 390.0,
                      height: 844.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: null,
                              top: 106.0,
                              right: null,
                              bottom: null,
                              width: 348.0,
                              height: 44.0,
                              child: TransformHelper.translate(
                                  x: 4.00,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedSelectyourcityWidget1()),
                            ),
                            Positioned(
                              left: 25.0,
                              top: 750.0,
                              right: null,
                              bottom: null,
                              width: 340.0,
                              height: 56.0,
                              child: GeneratedComponent2Widget10(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 175.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 36.0,
                              child: GeneratedSearchFieldWidget1(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 58.0,
                              right: null,
                              bottom: null,
                              width: 53.0,
                              height: 33.0,
                              child: GeneratedBackWidget16(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 238.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 454.0,
                              child: GeneratedFrame616Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
