import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mvpupdatedapp/generated16_childprofilewidget/generated/GeneratedComponent2Widget11.dart';
import 'package:flutterapp/mvpupdatedapp/generated16_childprofilewidget/generated/GeneratedTitleWidget8.dart';
import 'package:flutterapp/mvpupdatedapp/generated16_childprofilewidget/generated/GeneratedFrame634Widget.dart';
import 'package:flutterapp/mvpupdatedapp/generated16_childprofilewidget/generated/GeneratedFrame616Widget2.dart';
import 'package:flutterapp/mvpupdatedapp/generated16_childprofilewidget/generated/GeneratedSelectyourschoolWidget.dart';

/* Frame 16_child profile
    Autogenerated by FlutLab FTF Generator
  */
class Generated16_childprofileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 844.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 390.0,
                      height: 844.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: null,
                              top: 109.0,
                              right: null,
                              bottom: null,
                              width: 172.0,
                              height: 25.0,
                              child: TransformHelper.translate(
                                  x: -70.00,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedSelectyourschoolWidget()),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 750.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 54.0,
                              child: GeneratedComponent2Widget11(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 140.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 67.0,
                              child: GeneratedFrame634Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 238.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 454.0,
                              child: GeneratedFrame616Widget2(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 46.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 42.0,
                              child: GeneratedTitleWidget8(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
