import 'package:flutter/material.dart';
import 'package:flutterapp/mvpupdatedapp/generated37_childrenlistwidget/generated/GeneratedFrame613Widget5.dart';
import 'package:flutterapp/mvpupdatedapp/generated37_childrenlistwidget/generated/GeneratedFrame614Widget13.dart';
import 'package:flutterapp/mvpupdatedapp/generated37_childrenlistwidget/generated/GeneratedTitleWidget41.dart';
import 'package:flutterapp/mvpupdatedapp/generated37_childrenlistwidget/generated/GeneratedFrame613Widget4.dart';
import 'package:flutterapp/mvpupdatedapp/generated37_childrenlistwidget/generated/GeneratedRequestsWidget2.dart';

/* Frame 37_children list
    Autogenerated by FlutLab FTF Generator
  */
class Generated37_childrenlistWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 844.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 390.0,
                      height: 844.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 135.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 188.0,
                              child: GeneratedFrame613Widget4(),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 337.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 188.0,
                              child: GeneratedFrame614Widget13(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 539.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 188.0,
                              child: GeneratedFrame613Widget5(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 66.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 42.0,
                              child: GeneratedTitleWidget41(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 754.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 54.0,
                              child: GeneratedRequestsWidget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
