import 'package:flutter/material.dart';
import 'package:flutterapp/mvpupdatedapp/generated27_mainmenuwidget/generated/GeneratedFrame49Widget3.dart';
import 'package:flutterapp/mvpupdatedapp/generated27_mainmenuwidget/generated/GeneratedAhOranyim2Widget.dart';
import 'package:flutterapp/mvpupdatedapp/generated27_mainmenuwidget/generated/GeneratedFrame640Widget2.dart';
import 'package:flutterapp/mvpupdatedapp/generated27_mainmenuwidget/generated/GeneratedBasketballWidget14.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mvpupdatedapp/generated27_mainmenuwidget/generated/GeneratedSportWidget6.dart';
import 'package:flutterapp/mvpupdatedapp/generated27_mainmenuwidget/generated/GeneratedMessageforparentsWidget.dart';
import 'package:flutterapp/mvpupdatedapp/generated27_mainmenuwidget/generated/GeneratedSportclassratingWidget.dart';
import 'package:flutterapp/mvpupdatedapp/generated27_mainmenuwidget/generated/GeneratedInputtextWidget.dart';
import 'package:flutterapp/mvpupdatedapp/generated27_mainmenuwidget/generated/GeneratedAddressWidget6.dart';
import 'package:flutterapp/mvpupdatedapp/generated27_mainmenuwidget/generated/GeneratedFeedbackforBikeInternationalSchoolWidget.dart';
import 'package:flutterapp/mvpupdatedapp/generated27_mainmenuwidget/generated/GeneratedComponent64Widget1.dart';
import 'package:flutterapp/mvpupdatedapp/generated27_mainmenuwidget/generated/GeneratedComponent83Widget.dart';

/* Frame 27_Main menu
    Autogenerated by FlutLab FTF Generator
  */
class Generated27_MainmenuWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          clipBehavior: Clip.none,
          fit: StackFit.expand,
          alignment: Alignment.center,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 986.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 375.0,
                            height: 986.0,
                            child: Stack(
                                clipBehavior: Clip.none,
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 248, 251, 250),
                                    ),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 502.0,
                                    right: 0.0,
                                    bottom: null,
                                    width: null,
                                    height: 25.0,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width =
                                          constraints.maxWidth * 0.44;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth * 0.064,
                                            y: 0,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              child:
                                                  GeneratedSportclassratingWidget(),
                                            ))
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 136.0,
                                    right: 0.0,
                                    bottom: null,
                                    width: null,
                                    height: 48.0,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width =
                                          constraints.maxWidth *
                                              0.8773333333333333;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth * 0.064,
                                            y: 0,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              child:
                                                  GeneratedFeedbackforBikeInternationalSchoolWidget(),
                                            ))
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 611.0,
                                    right: 0.0,
                                    bottom: null,
                                    width: null,
                                    height: 25.0,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width =
                                          constraints.maxWidth *
                                              0.5093333333333333;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth * 0.064,
                                            y: 0,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              child:
                                                  GeneratedMessageforparentsWidget(),
                                            ))
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 24.0,
                                    top: 650.0,
                                    right: 24.0,
                                    bottom: null,
                                    width: null,
                                    height: 201.0,
                                    child: GeneratedInputtextWidget(),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: 202.0,
                                    right: null,
                                    bottom: null,
                                    width: 52.0,
                                    height: 21.0,
                                    child: TransformHelper.translate(
                                        x: 31.50,
                                        y: 0.00,
                                        z: 0,
                                        child: GeneratedSportWidget6()),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: 202.0,
                                    right: null,
                                    bottom: null,
                                    width: 72.0,
                                    height: 21.0,
                                    child: TransformHelper.translate(
                                        x: -126.50,
                                        y: 0.00,
                                        z: 0,
                                        child: GeneratedAddressWidget6()),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: 222.0,
                                    right: null,
                                    bottom: null,
                                    width: 86.0,
                                    height: 21.0,
                                    child: TransformHelper.translate(
                                        x: 48.50,
                                        y: 0.00,
                                        z: 0,
                                        child: GeneratedBasketballWidget14()),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: 222.0,
                                    right: null,
                                    bottom: null,
                                    width: 115.0,
                                    height: 18.0,
                                    child: TransformHelper.translate(
                                        x: -105.00,
                                        y: 0.00,
                                        z: 0,
                                        child: GeneratedAhOranyim2Widget()),
                                  ),
                                  Positioned(
                                    left: 17.0,
                                    top: 286.0,
                                    right: 16.0,
                                    bottom: null,
                                    width: null,
                                    height: 56.0,
                                    child: GeneratedComponent64Widget1(),
                                  ),
                                  Positioned(
                                    left: 16.0,
                                    top: 394.0,
                                    right: 17.0,
                                    bottom: null,
                                    width: null,
                                    height: 56.0,
                                    child: GeneratedComponent83Widget(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: null,
              right: null,
              bottom: 0.0,
              width: 375.0,
              height: 110.0,
              child: GeneratedFrame640Widget2(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 128.0,
              child: GeneratedFrame49Widget3(),
            )
          ]),
    ));
  }
}
