import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mvpupdatedapp/generated6_forgotpasswordwidget/generated/GeneratedSystemFeedbackblockWidget1.dart';
import 'package:flutterapp/mvpupdatedapp/generated6_forgotpasswordwidget/generated/GeneratedNewpasswordWidget.dart';
import 'package:flutterapp/mvpupdatedapp/generated6_forgotpasswordwidget/generated/GeneratedInputWidget.dart';
import 'package:flutterapp/mvpupdatedapp/generated6_forgotpasswordwidget/generated/GeneratedBackWidget6.dart';
import 'package:flutterapp/mvpupdatedapp/generated6_forgotpasswordwidget/generated/GeneratedComponent2Widget4.dart';

/* Frame 6_forgot password
    Autogenerated by FlutLab FTF Generator
  */
class Generated6_forgotpasswordWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child: Stack(
            clipBehavior: Clip.none,
            fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 11.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 33.0,
                child: GeneratedBackWidget6(),
              ),
              Positioned(
                left: null,
                top: 111.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 43.0,
                child: TransformHelper.translate(
                    x: 3.00,
                    y: 0.00,
                    z: 0,
                    child: GeneratedNewpasswordWidget()),
              ),
              Positioned(
                left: 31.0,
                top: 192.0,
                right: 32.0,
                bottom: null,
                width: null,
                height: 56.0,
                child: GeneratedInputWidget(),
              ),
              Positioned(
                left: 31.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 78.0,
                child: GeneratedSystemFeedbackblockWidget1(),
              ),
              Positioned(
                left: 31.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 54.0,
                child: GeneratedComponent2Widget4(),
              )
            ]),
      ),
    ));
  }
}
