import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mvpupdatedapp/generated42_sportcreatedwidget/generated/GeneratedSport1Widget.dart';
import 'package:flutterapp/mvpupdatedapp/generated42_sportcreatedwidget/generated/GeneratedAccountsuccessfullyregisteredWidget.dart';
import 'package:flutterapp/mvpupdatedapp/generated42_sportcreatedwidget/generated/GeneratedComponent2Widget.dart';
import 'package:flutterapp/mvpupdatedapp/generated42_sportcreatedwidget/generated/GeneratedSportsuccessfullycreatedWidget.dart';

/* Frame 42_sport created
    Autogenerated by FlutLab FTF Generator
  */
class Generated42_sportcreatedWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child: Stack(clipBehavior: Clip.none, fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 83, 219, 146),
            ),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(builder: (BuildContext context, BoxConstraints constraints) {
              final double width = constraints.maxWidth * 0.717948717948718;

              final double height = constraints.maxHeight * 0.04028436018957346;

              return Stack(children: [
                TransformHelper.translate(
                    x: constraints.maxWidth * 0.13333333333333333,
                    y: constraints.maxHeight * 0.2950236966824645,
                    z: 0,
                    child: Container(
                      width: width,
                      height: height,
                      child: GeneratedSportsuccessfullycreatedWidget(),
                    ))
              ]);
            }),
          ),
          Positioned(
            left: 8.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 464.0,
            child: GeneratedAccountsuccessfullyregisteredWidget(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(builder: (BuildContext context, BoxConstraints constraints) {
              final double width = constraints.maxWidth * 0.4846153846153846;

              final double height = constraints.maxHeight * 0.06398104265402843;

              return Stack(children: [
                TransformHelper.translate(
                    x: constraints.maxWidth * 0.26153846153846155,
                    y: constraints.maxHeight * 0.9075829383886256,
                    z: 0,
                    child: Container(
                      width: width,
                      height: height,
                      child: GeneratedComponent2Widget(),
                    ))
              ]);
            }),
          ),
          Positioned(
            left: 33.0,
            top: 281.0,
            right: null,
            bottom: null,
            width: 327.0,
            height: 485.0,
            child: GeneratedSport1Widget(),
          )
        ]),
      ),
    ));
  }
}
