import 'package:flutter/material.dart';
import 'package:flutterapp/mvpupdatedapp/generated2_signinwidget/generated/GeneratedHUGINWidget1.dart';
import 'package:flutterapp/mvpupdatedapp/generated2_signinwidget/generated/GeneratedEllipse130Widget1.dart';
import 'package:flutterapp/mvpupdatedapp/generated2_signinwidget/generated/GeneratedEllipse128Widget1.dart';
import 'package:flutterapp/mvpupdatedapp/generated2_signinwidget/generated/GeneratedYourpersonalassistanttotheworldofyourchildssportclasses1.dart';
import 'package:flutterapp/mvpupdatedapp/generated2_signinwidget/generated/LogInButton.dart';
import 'package:flutterapp/mvpupdatedapp/generated2_signinwidget/generated/GeneratedEllipse129Widget1.dart';
import 'package:flutterapp/mvpupdatedapp/generated2_signinwidget/generated/GeneratedEllipse127Widget1.dart';
import 'package:flutterapp/mvpupdatedapp/generated2_signinwidget/generated/CreateAccountButton.dart';

/* Frame 2_sign in
    Autogenerated by FlutLab FTF Generator
  */
class Generated2_signinWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child: Stack(
            clipBehavior: Clip.none,
            fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 32.0,
                top: 711.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 54.0,
                child: GeneratedComponent3Widget(),
              ),
              Positioned(
                left: 32.0,
                top: 649.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 54.0,
                child: GeneratedComponent2Widget(),
              ),
              Positioned(
                left: -79.0,
                top: 157.791015625,
                right: null,
                bottom: null,
                width: 466.7176818847656,
                height: 440.7015686035156,
                child: GeneratedEllipse129Widget1(),
              ),
              Positioned(
                left: 252.0323486328125,
                top: 101.81494140625,
                right: null,
                bottom: null,
                width: 334.461669921875,
                height: 315.81787109375,
                child: GeneratedEllipse128Widget1(),
              ),
              Positioned(
                left: 83.95703125,
                top: 207.71044921875,
                right: null,
                bottom: null,
                width: 222.0,
                height: 235.0,
                child: GeneratedEllipse127Widget1(),
              ),
              Positioned(
                left: 105.220703125,
                top: 322.0517578125,
                right: null,
                bottom: null,
                width: 124.0,
                height: 130.0,
                child: GeneratedEllipse130Widget1(),
              ),
              Positioned(
                left: 116.0,
                top: 489.0,
                right: null,
                bottom: null,
                width: 159.0,
                height: 36.0,
                child: GeneratedHUGINWidget1(),
              ),
              Positioned(
                left: 67.0,
                top: 539.0,
                right: null,
                bottom: null,
                width: 258.0,
                height: 77.0,
                child:
                    GeneratedYourpersonalassistanttotheworldofyourchildssportclasses1(),
              )
            ]),
      ),
    ));
  }
}
