import 'package:flutter/material.dart';
import 'package:flutterapp/mvpupdatedapp/generated11_createaccountwidget/generated/GeneratedTitleWidget2.dart';
import 'package:flutterapp/mvpupdatedapp/generated11_createaccountwidget/generated/GeneratedSystemFeedbackblockWidget2.dart';
import 'package:flutterapp/mvpupdatedapp/generated11_createaccountwidget/generated/GeneratedComponent2Widget9.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mvpupdatedapp/generated11_createaccountwidget/generated/GeneratedComponent7Widget1.dart';
import 'package:flutterapp/mvpupdatedapp/generated11_createaccountwidget/generated/GeneratedEnteracodeWidget1.dart';
import 'package:flutterapp/mvpupdatedapp/generated11_createaccountwidget/generated/GeneratedResentcodeagainWidget.dart';

/* Frame 11_create account
    Autogenerated by FlutLab FTF Generator
  */
class Generated11_createaccountWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child: Stack(
            clipBehavior: Clip.none,
            fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: null,
                top: 98.0,
                right: null,
                bottom: null,
                width: 199.0,
                height: 41.0,
                child: TransformHelper.translate(
                    x: -63.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedEnteracodeWidget1()),
              ),
              Positioned(
                left: 8.0,
                top: 48.0,
                right: 7.0,
                bottom: null,
                width: null,
                height: 42.0,
                child: GeneratedTitleWidget2(),
              ),
              Positioned(
                left: 32.0,
                top: 257.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 78.0,
                child: GeneratedSystemFeedbackblockWidget2(),
              ),
              Positioned(
                left: 32.0,
                top: 177.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 56.0,
                child: GeneratedComponent7Widget1(),
              ),
              Positioned(
                left: 32.0,
                top: 448.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 54.0,
                child: GeneratedComponent2Widget9(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.29743589743589743;

                  final double height =
                      constraints.maxHeight * 0.02132701421800948;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3564102564102564,
                        y: constraints.maxHeight * 0.476303317535545,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedResentcodeagainWidget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
