import 'package:flutter/material.dart';
import 'package:flutterapp/mvpupdatedapp/generated43_sportswidget/generated/GeneratedComponent2Widget4.dart';
import 'package:flutterapp/mvpupdatedapp/generated43_sportswidget/generated/GeneratedHUGINWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mvpupdatedapp/generated43_sportswidget/generated/GeneratedSport1Widget2.dart';
import 'package:flutterapp/mvpupdatedapp/generated43_sportswidget/generated/GeneratedSport1Widget4.dart';
import 'package:flutterapp/mvpupdatedapp/generated43_sportswidget/generated/GeneratedNameWidget1.dart';

/* Frame 43_sports
    Autogenerated by FlutLab FTF Generator
  */
class Generated43_sportsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1389.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 390.0,
                      height: 1389.0,
                      child: Stack(clipBehavior: Clip.none, fit: StackFit.expand, alignment: Alignment.center, children: [
                        ClipRRect(
                          borderRadius: BorderRadius.zero,
                          child: Container(
                            color: Color.fromARGB(255, 255, 255, 255),
                          ),
                        ),
                        Positioned(
                          left: 30.0,
                          top: 210.0,
                          right: null,
                          bottom: null,
                          width: 327.0,
                          height: 485.0,
                          child: GeneratedSport1Widget2(),
                        ),
                        Positioned(
                          left: 30.0,
                          top: 715.0,
                          right: null,
                          bottom: null,
                          width: 327.0,
                          height: 485.0,
                          child: GeneratedSport1Widget4(),
                        ),
                        Positioned(
                          left: 137.0,
                          top: 135.0,
                          right: null,
                          bottom: null,
                          width: 119.0,
                          height: 39.0,
                          child: GeneratedNameWidget1(),
                        ),
                        Positioned(
                          left: 116.0,
                          top: 63.0,
                          right: null,
                          bottom: null,
                          width: 159.0,
                          height: 36.0,
                          child: GeneratedHUGINWidget2(),
                        ),
                        Positioned(
                          left: 0.0,
                          top: 0.0,
                          right: 0.0,
                          bottom: 0.0,
                          width: null,
                          height: null,
                          child: LayoutBuilder(builder: (BuildContext context, BoxConstraints constraints) {
                            final double width = constraints.maxWidth * 0.4846153846153846;

                            final double height = constraints.maxHeight * 0.057877817284382876;

                            return Stack(children: [
                              TransformHelper.translate(
                                  x: constraints.maxWidth * 0.25384615384615383,
                                  y: constraints.maxHeight * 0.8992497201786357,
                                  z: 0,
                                  child: Container(
                                    width: width,
                                    height: height,
                                    child: GeneratedComponent2Widget4(),
                                  ))
                            ]);
                          }),
                        )
                      ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
