import 'package:flutter/material.dart';
import 'package:flutterapp/mvpupdatedapp/generated33_trainerwidget/generated/GeneratedNowisthetimetochooseasportclubWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mvpupdatedapp/generated33_trainerwidget/generated/GeneratedTrainersprofilesuccessfullyaddedWidget.dart';
import 'package:flutterapp/mvpupdatedapp/generated33_trainerwidget/generated/GeneratedFrame653Widget1.dart';
import 'package:flutterapp/mvpupdatedapp/generated33_trainerwidget/generated/GeneratedComponent2Widget19.dart';

/* Frame 33_Trainer
    Autogenerated by FlutLab FTF Generator
  */
class Generated33_TrainerWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child: Stack(
            clipBehavior: Clip.none,
            fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 83, 219, 146),
                ),
              ),
              Positioned(
                left: 7.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 464.0,
                child: GeneratedFrame653Widget1(),
              ),
              Positioned(
                left: 52.0,
                top: 569.0,
                right: null,
                bottom: null,
                width: 288.0,
                height: 48.0,
                child: GeneratedNowisthetimetochooseasportclubWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.6897435897435897;

                  final double height =
                      constraints.maxHeight * 0.06753554502369669;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.1564102564102564,
                        y: constraints.maxHeight * 0.5971563981042654,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child:
                              GeneratedTrainersprofilesuccessfullyaddedWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 31.0,
                top: 677.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 54.0,
                child: GeneratedComponent2Widget19(),
              )
            ]),
      ),
    ));
  }
}
