import 'package:flutter/material.dart';
import 'package:flutterapp/mvpupdatedapp/generated26_mainmenuwidget/generated/GeneratedComponent72Widget.dart';
import 'package:flutterapp/mvpupdatedapp/generated26_mainmenuwidget/generated/GeneratedFrame640Widget1.dart';
import 'package:flutterapp/mvpupdatedapp/generated26_mainmenuwidget/generated/GeneratedComponent71Widget.dart';
import 'package:flutterapp/mvpupdatedapp/generated26_mainmenuwidget/generated/GeneratedTitleWidget24.dart';
import 'package:flutterapp/mvpupdatedapp/generated26_mainmenuwidget/generated/GeneratedComponent6Widget8.dart';

/* Frame 26_Main menu
    Autogenerated by FlutLab FTF Generator
  */
class Generated26_MainmenuWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          clipBehavior: Clip.none,
          fit: StackFit.expand,
          alignment: Alignment.center,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1136.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 375.0,
                            height: 1136.0,
                            child: Stack(
                                clipBehavior: Clip.none,
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 255, 255, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: null,
                                    right: null,
                                    bottom: 0.0,
                                    width: 375.0,
                                    height: 63.0,
                                    child: GeneratedComponent6Widget8(),
                                  ),
                                  Positioned(
                                    left: -1.0,
                                    top: null,
                                    right: null,
                                    bottom: 65.0,
                                    width: 375.0,
                                    height: 94.0,
                                    child: GeneratedFrame640Widget1(),
                                  ),
                                  Positioned(
                                    left: 24.0,
                                    top: 568.0,
                                    right: null,
                                    bottom: null,
                                    width: 327.0,
                                    height: 391.0,
                                    child: GeneratedComponent72Widget(),
                                  ),
                                  Positioned(
                                    left: 24.0,
                                    top: 127.0,
                                    right: null,
                                    bottom: null,
                                    width: 327.0,
                                    height: 391.0,
                                    child: GeneratedComponent71Widget(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: 54.0,
              right: -15.0,
              bottom: null,
              width: null,
              height: 42.0,
              child: GeneratedTitleWidget24(),
            )
          ]),
    ));
  }
}
