import 'package:flutter/material.dart';
import 'package:flutterapp/mvpupdatedapp/generated4_forgotpasswordwidget/generated/GeneratedBackWidget2.dart';
import 'package:flutterapp/mvpupdatedapp/generated4_forgotpasswordwidget/generated/GeneratedForgotpasswordWidget2.dart';
import 'package:flutterapp/mvpupdatedapp/generated4_forgotpasswordwidget/generated/GeneratedComponent2Widget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mvpupdatedapp/generated4_forgotpasswordwidget/generated/GeneratedEnterphonenumWidget.dart';
import 'package:flutterapp/mvpupdatedapp/generated4_forgotpasswordwidget/generated/GeneratedInfoblockWidget.dart';

/* Frame 4_forgot password
    Autogenerated by FlutLab FTF Generator
  */
class Generated4_forgotpasswordWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child: Stack(
            clipBehavior: Clip.none,
            fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 3.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 33.0,
                child: GeneratedBackWidget2(),
              ),
              Positioned(
                left: 29.0,
                top: 450.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 54.0,
                child: GeneratedComponent2Widget2(),
              ),
              Positioned(
                left: null,
                top: 133.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 43.0,
                child: TransformHelper.translate(
                    x: 1.00,
                    y: 0.00,
                    z: 0,
                    child: GeneratedForgotpasswordWidget2()),
              ),
              Positioned(
                left: 29.0,
                top: 294.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 99.0,
                child: GeneratedInfoblockWidget(),
              ),
              Positioned(
                left: 29.0,
                top: 206.0,
                right: 34.0,
                bottom: null,
                width: null,
                height: 56.0,
                child: GeneratedEnterphonenumWidget(),
              )
            ]),
      ),
    ));
  }
}
