import 'package:flutter/material.dart';
import 'package:flutterapp/mvpupdatedapp/generated14_childprofilewidget/generated/GeneratedComponent60Widget5.dart';
import 'package:flutterapp/mvpupdatedapp/generated14_childprofilewidget/generated/GeneratedComponent60Widget2.dart';
import 'package:flutterapp/mvpupdatedapp/generated14_childprofilewidget/generated/GeneratedFrame615Widget4.dart';
import 'package:flutterapp/mvpupdatedapp/generated14_childprofilewidget/generated/GeneratedComponent61Widget.dart';
import 'package:flutterapp/mvpupdatedapp/generated14_childprofilewidget/generated/GeneratedComponent3Widget4.dart';
import 'package:flutterapp/mvpupdatedapp/generated14_childprofilewidget/generated/GeneratedComponent60Widget3.dart';
import 'package:flutterapp/mvpupdatedapp/generated14_childprofilewidget/generated/GeneratedComponent60Widget4.dart';
import 'package:flutterapp/mvpupdatedapp/generated14_childprofilewidget/generated/GeneratedTitleWidget6.dart';

/* Frame 14_child profile
    Autogenerated by FlutLab FTF Generator
  */
class Generated14_childprofileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 844.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 390.0,
                      height: 844.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 26.0,
                              top: 647.0,
                              right: 22.0,
                              bottom: null,
                              width: null,
                              height: 56.0,
                              child: GeneratedComponent60Widget2(),
                            ),
                            Positioned(
                              left: 26.0,
                              top: 551.0,
                              right: 22.0,
                              bottom: null,
                              width: null,
                              height: 56.0,
                              child: GeneratedComponent60Widget3(),
                            ),
                            Positioned(
                              left: 28.0,
                              top: 455.0,
                              right: 20.0,
                              bottom: null,
                              width: null,
                              height: 56.0,
                              child: GeneratedComponent61Widget(),
                            ),
                            Positioned(
                              left: 28.0,
                              top: 359.0,
                              right: 20.0,
                              bottom: null,
                              width: null,
                              height: 56.0,
                              child: GeneratedComponent60Widget4(),
                            ),
                            Positioned(
                              left: 28.0,
                              top: 263.0,
                              right: 20.0,
                              bottom: null,
                              width: null,
                              height: 56.0,
                              child: GeneratedComponent60Widget5(),
                            ),
                            Positioned(
                              left: 142.0,
                              top: 120.0,
                              right: null,
                              bottom: null,
                              width: 106.0,
                              height: 102.0,
                              child: GeneratedFrame615Widget4(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 53.0,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 42.0,
                              child: GeneratedTitleWidget6(),
                            ),
                            Positioned(
                              left: 32.0,
                              top: null,
                              right: null,
                              bottom: 40.0,
                              width: 327.0,
                              height: 54.0,
                              child: GeneratedComponent3Widget4(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
